--- #YAML:1.0
name:                POE-XS-Loop-Poll
version:             0.002
abstract:            XS loop implementation for POE
license:             perl
author:              
    - Tony Cook <tonyc@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    POE:                           1.0003
    POE::Test::Loops:              0.99
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
configure_requires:
  POE::Test::Loops: 0.99
build_requires:
  POE::Test::Loops: 0.99
